from pathlib import Path
import os

BASE_DIR = Path(__file__).resolve().parent.parent

# Model paths
MODELS_DIR = BASE_DIR / "models"
RF_MODEL_PATH = MODELS_DIR / "random_forest_regressor_TUNED.joblib"
GB_MODEL_PATH = MODELS_DIR / "gradient_boosting_regressor_TUNED.joblib"
LSTM_MODEL_PATH = MODELS_DIR / "lstm_model.keras"
METRICS_PATH = MODELS_DIR / "test_metrics_default.csv"

# Sample data
SAMPLE_DATA_PATH = BASE_DIR / "data" / "sample_data.json"

# LSTM config
LSTM_WINDOW = 24

# Scaler parameters (computed from training set of UCI dataset)
# Generated by generate_sample_data.py
SCALER_MEAN = float(os.environ.get("SCALER_MEAN", "1.086397"))
SCALER_STD = float(os.environ.get("SCALER_STD", "0.929282"))

# Feature columns for tree models (MUST match exact order from training)
TREE_FEATURE_COLS = [
    "Global_reactive_power", "Voltage", "Global_intensity",
    "Sub_metering_1", "Sub_metering_2", "Sub_metering_3",
    "hour", "dayofweek", "is_weekend", "month",
    "Global_active_power_lag1", "Global_active_power_lag2",
    "Global_active_power_lag3", "Global_active_power_lag6",
    "Global_active_power_lag12", "Global_active_power_lag24",
    "Global_active_power_rollmean3", "Global_active_power_rollstd3",
    "Global_active_power_rollmean6", "Global_active_power_rollstd6",
    "Global_active_power_rollmean12", "Global_active_power_rollstd12",
    "Global_active_power_rollmean24", "Global_active_power_rollstd24",
]

# CORS
FRONTEND_URL = os.environ.get("FRONTEND_URL", "https://prediksi-konsumsi-energi-rumah-tangga.vercel.app")
